### ISSUE TITLE
error when launching "python -m pyrl.rlglue.run --help" after install

### ISSUE THREAD

**Issue by VinF** [amarack/python-rl#3]
Hi
In the file "pyrl/basis/tilecode.py", line 4, in <module>, there is "from CTiles import tiles" but that file doesn't exist (see the error I got below). I've imported the whole folder and it removes the error.
Best,
Vincent

python -m pyrl.rlglue.run --help

Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/vincent/Documents/python-rl-master/pyrl/rlglue/run.py", line 13, in <module>
    from pyrl.agents import *
  File "pyrl/agents/modelbased.py", line 17, in <module>
    from pyrl.agents.planners import fitted_qiteration
  File "pyrl/agents/planners/fitted_qiteration.py", line 9, in <module>
    import pyrl.basis.tilecode as tilecode
  File "pyrl/basis/tilecode.py", line 4, in <module>
    from CTiles import tiles
ImportError: cannot import name tiles

**Comment by pierrelux** [comment]
You probably want to go under pyrl/basis/CTiles and run "cmake CMakelists.txt" and "make".

The tile coding is implemented in C .

**Comment by okkhoy** [comment]
Hi! I know this is an old thread, but here I go!

When I use the same method in Windows (Cygwin) it seems to not work. 
The Agents list does not still contain Qlearning, SARSA etc. 

Can you help me on this front? Even an idea to tell how to make it work is fine, I can patch the files and release it back here.

**Comment by PencilAndBike** [comment]
It can run under linux for the make file is not suitable for windows
