### ISSUE TITLE
Error of Runing python -m pyrl.rlglue.run

### ISSUE THREAD

**Issue by gaoyuankidult** [amarack/python-rl#5]
I would like test REINFORCE algorithm proposed by Williams

after excuting python -m pyrl.rlglue.run

I selected (5): Cart Pole
then I selected  (14): REINFORCE
then I selected (1): Episodic

it gives me an error as 

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/deepthree/Desktop/deepcontrol/python-rl/pyrl/rlglue/run.py", line 126, in <module>
    run(_config,local=args.local, result_file=args.output)
  File "/home/deepthree/Desktop/deepcontrol/python-rl/pyrl/rlglue/run.py", line 85, in run
    experiment = exp(config, agent=agent(_*a_args),
  File "pyrl/agents/skeleton_agent.py", line 31, in __init__
    self.init_parameters()
  File "pyrl/agents/policy_gradient.py", line 123, in init_parameters
    super(REINFORCE, self).init_parameters(self)
TypeError: init_parameters() takes exactly 1 argument (2 given)

Is this a bug ?
In fact, if I select other environment (e.g. 1: 3D Mountain Car), it gives me same error

**Comment by PencilAndBike** [comment]
Just let 'super(REINFORCE, self).init_parameters(self)' be 'super(REINFORCE, self).init_parameters()'
Of course, such problem would happen in other places. Just do it like above. It can run, but the result is not good.
