### ISSUE TITLE
Error when running - No module named rlglue.agent.Agent 

### ISSUE THREAD

**Issue by beeva-jorgedelval** [amarack/python-rl#7]
Hello,

When I try to run with python -m pyrl.rlglue.run I get the following traceback:

Traceback (most recent call last):
  File "/home/jorgedelval/miniconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/jorgedelval/miniconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/jorgedelval/edxai/python-rl/pyrl/rlglue/run.py", line 13, in <module>
    from pyrl.agents import *
  File "pyrl/agents/skeleton_agent.py", line 13, in <module>
    from rlglue.agent.Agent import Agent
ImportError: No module named rlglue.agent.Agent

I have installed pyrl with "make" inside the pyrl directory. I'm on Ubuntu 16 64bits.

Did I miss something?

Thank you very much

**Comment by Jiawen-Yan** [comment]
Encounter the same problem

**Comment by Jiawen-Yan** [comment]
@beeva-jorgedelval  have you solved the problem? Thanks

**Comment by gsc579** [comment]
me to. can't find    rlglue.agent.Agent
